export const tournamentActionTypes = {
  NEW_TOURNAMENT_SUBMIT: 'NEW_TOURNAMENT_SUBMIT',
  NEW_TOURNAMENT_SUBMIT_START: 'NEW_TOURNAMENT_SUBMIT_START',
  NEW_TOURNAMENT_SUBMIT_SUCCESS: 'NEW_TOURNAMENT_SUBMIT_SUCCESS',
  NEW_TOURNAMENT_SUBMIT_FAIL: 'NEW_TOURNAMENT_SUBMIT_FAIL',

  NEW_TOURNAMENT_URL_CHANGE: 'NEW_TOURNAMENT_URL_CHANGE',
  NEW_TOURNAMENT_URL_CHANGE_START: 'NEW_TOURNAMENT_URL_CHANGE_START',
  NEW_TOURNAMENT_URL_CHANGE_AVAILABLE: 'NEW_TOURNAMENT_URL_CHANGE_AVAILABLE',
  NEW_TOURNAMENT_URL_CHANGE_NOT_AVAILABLE: 'NEW_TOURNAMENT_URL_CHANGE_NOT_AVAILABLE',

  TOURNAMENT_PARTICIPANTS_INPUT_CHANGE: 'TOURNAMENT_PARTICIPANTS_INPUT_CHANGE',
  TOURNAMENT_DRAW_BRACKET: 'TOURNAMENT_DRAW_BRACKET',

  LOAD_TOURNAMENT: 'LOAD_TOURNAMENT',
  LOAD_TOURNAMENT_START: 'LOAD_TOURNAMENT_START',
  LOAD_TOURNAMENT_SUCCESS: 'LOAD_TOURNAMENT_SUCCESS',
  LOAD_TOURNAMENT_FAIL: 'LOAD_TOURNAMENT_FAIL',

  UPDATE_BRACKET: 'UPDATE_BRACKET',
  UPDATE_BRACKET_START: 'UPDATE_BRACKET_START',
  UPDATE_BRACKET_SUCCESS: 'UPDATE_BRACKET_SUCCESS',
  UPDATE_BRACKET_FAIL: 'UPDATE_BRACKET_FAIL',

  REPORT_MATCH_SCORE: 'REPORT_MATCH_SCORE',
  REPORT_MATCH_SCORE_START: 'REPORT_MATCH_SCORE_START',
  REPORT_MATCH_SCORE_SUCCESS: 'REPORT_MATCH_SCORE_SUCCESS',
  REPORT_MATCH_SCORE_END_TOURNAMENT: 'REPORT_MATCH_SCORE_END_TOURNAMENT',
  REPORT_MATCH_SCORE_FAIL: 'REPORT_MATCH_SCORE_FAIL',
  CLEAN_REPORT_FLAGS: 'CLEAN_REPORT_FLAGS',

  UPDATE_PLAYER_HIGHLIGHT_IN_BRACKET: 'UPDATE_PLAYER_HIGHLIGHT_IN_BRACKET'
}
