export const tournamentActionTypes = {
  NEW_TOURNAMENT_SUBMIT: 'NEW_TOURNAMENT_SUBMIT',
  NEW_TOURNAMENT_SUBMIT_START: 'NEW_TOURNAMENT_SUBMIT_START',
  NEW_TOURNAMENT_SUBMIT_SUCCESS: 'NEW_TOURNAMENT_SUBMIT_SUCCESS',
  NEW_TOURNAMENT_SUBMIT_FAIL: 'NEW_TOURNAMENT_SUBMIT_FAIL',

  NEW_TOURNAMENT_URL_CHANGE: 'NEW_TOURNAMENT_URL_CHANGE',
  NEW_TOURNAMENT_URL_CHANGE_START: 'NEW_TOURNAMENT_URL_CHANGE_START',
  NEW_TOURNAMENT_URL_CHANGE_AVAILABLE: 'NEW_TOURNAMENT_URL_CHANGE_AVAILABLE',
  NEW_TOURNAMENT_URL_CHANGE_NOT_AVAILABLE: 'NEW_TOURNAMENT_URL_CHANGE_NOT_AVAILABLE',

  TOURNAMENT_PARTICIPANTS_INPUT_CHANGE: 'TOURNAMENT_PARTICIPANTS_INPUT_CHANGE',
  TOURNAMENT_DRAW_BRACKET: 'TOURNAMENT_DRAW_BRACKET',

  LOAD_TOURNAMENT: 'LOAD_TOURNAMENT',
  LOAD_TOURNAMENT_START: 'LOAD_TOURNAMENT_START',
  LOAD_TOURNAMENT_SUCCESS: 'LOAD_TOURNAMENT_SUCCESS',
  LOAD_TOURNAMENT_FAIL: 'LOAD_TOURNAMENT_FAIL',

  START_TOURNAMENT: 'START_TOURNAMENT',
  START_TOURNAMENT_START: 'START_TOURNAMENT_START',
  START_TOURNAMENT_SUCCESS: 'START_TOURNAMENT_SUCCESS',
  START_TOURNAMENT_FAIL: 'START_TOURNAMENT_FAIL'
}
