export const tournamentActionTypes = {
  NEW_TOURNAMENT_SUBMIT: 'NEW_TOURNAMENT_SUBMIT',
  NEW_TOURNAMENT_SUBMIT_START: 'NEW_TOURNAMENT_SUBMIT_START',
  NEW_TOURNAMENT_SUBMIT_SUCCESS: 'NEW_TOURNAMENT_SUBMIT_SUCCESS',
  NEW_TOURNAMENT_SUBMIT_FAIL: 'NEW_TOURNAMENT_SUBMIT_FAIL',
  NEW_TOURNAMENT_URL_CHANGE: 'NEW_TOURNAMENT_URL_CHANGE',
  NEW_TOURNAMENT_URL_CHANGE_START: 'NEW_TOURNAMENT_URL_CHANGE_START',
  NEW_TOURNAMENT_URL_CHANGE_AVAILABLE: 'NEW_TOURNAMENT_URL_CHANGE_AVAILABLE',
  NEW_TOURNAMENT_URL_CHANGE_NOT_AVAILABLE: 'NEW_TOURNAMENT_URL_CHANGE_NOT_AVAILABLE'
}
